version: '2'

services:
    mongo:
        container_name: pefi_mongo
        image: mongo:latest
        ports:
            - 27017:27017
        volumes:
            - "./mongo/db/:/data/db"

    nginx:
        build: ./nginx
        container_name: pefi_nginx
        links:
            - users
        ports:
            - 80:80

    users:
        build: ./users
        container_name: pefi_users
        environment:
            - loglevel=none
            - NODE_CONFIG_DIR=/src/app/config/
        volumes:
            - "./users:/src/app"
        working_dir: "/src/app"
        command: npm run start:dev
